Resources:
  blogTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: ${self:custom.deletionPolicy.${opt:stage}}
    UpdateReplacePolicy: ${self:custom.updatePolicy.${opt:stage}}
    Properties:
      TableName: ${env:APP_NAME}-${opt:stage}-blog
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: publishedAt
          AttributeType: S
        - AttributeName: authorId
          AttributeType: S
        - AttributeName: content
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PublishedAtIndex
          KeySchema:
            - AttributeName: publishedAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: AuthorIndex
          KeySchema:
            - AttributeName: authorId
              KeyType: HASH
            - AttributeName: publishedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ContentSearchIndex
          KeySchema:
            - AttributeName: content
              KeyType: HASH
            - AttributeName: publishedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
